# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('token', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='token')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='\u5907\u6ce8')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('IDcard', models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1')),
                ('gender', models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], default='N', max_length=1, verbose_name='\u6027\u522b')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5730\u5740')),
                ('QQ', models.CharField(blank=True, default='88888888', max_length=30, null=True, verbose_name='QQ\u53f7')),
                ('MBWT', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5bc6\u4fdd\u95ee\u9898')),
                ('MBDA', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5bc6\u4fdd\u7b54\u6848')),
                ('retryCount', models.IntegerField(default=0, verbose_name='\u51fa\u9519\u6b21\u6570')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
