# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0002_auto_20161125_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='IDcard',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='MBDA',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5bc6\u4fdd\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='MBWT',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5bc6\u4fdd\u95ee\u9898'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='QQ',
            field=models.CharField(blank=True, default='88888888', max_length=30, null=True, verbose_name='QQ\u53f7'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 25, 7, 1, 9, 840000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], default='N', max_length=1, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='memo',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='zhouzhou', max_length=32, verbose_name='\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='retryCount',
            field=models.IntegerField(default=0, verbose_name='\u51fa\u9519\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='token'),
        ),
    ]
